version: "2.2"

services:
  postgres_db:
    container_name: rl_postgres_database
    image: postgres:14
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 30s
      interval: 30s
      retries: 3
    volumes:
      - dj_postgres_data:/var/lib/postgresql/data/
      - ./assets/db:/docker-entrypoint-initdb.d/
    restart:
      always

    # Spring Boot Container

volumes:
  dj_postgres_data:
