version: "1"

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=ref_letters_db
    volumes:
      - ./assets/db:/docker-entrypoint-initdb.d
      - dj_postgres_data:/var/lib/postgresql/data/

volumes:
  dj_postgres_data: